import { z } from "zod";
import { getAiAnalytics, askHrCopilot, listCopilotConversations, listCopilotHistory, deleteCopilotConversationAction, clearCopilotHistoryAction, generateAiInsights, summarizeLeaveForApprover } from "@/lib/actions/ai";
import { changePasswordAction, signUpOrganizationAction } from "@/lib/actions/auth";
import { getAdminDashboard, getEmployeeDashboard } from "@/lib/actions/dashboard";
import {
  listMyNotifications,
  markNotificationReadAction,
  markAllNotificationsReadAction,
  deleteNotificationAction,
  clearNotificationsAction,
  getNotificationPreferences,
  saveNotificationPreferencesAction,
  createAnnouncementAction,
} from "@/lib/actions/notifications";
import { listAllocations, upsertAllocationAction, decideAllocationAction } from "@/lib/actions/people/allocations";
import {
  listAttendanceLogs,
  getAttendanceAction,
  listMyAttendance,
  getTodayAttendance,
  upsertAttendanceAction,
  clockInAction,
  clockOutAction,
  listAttendanceEmployees,
} from "@/lib/actions/people/attendance";
import { listContracts, getContractAction, getContractFormOptions, upsertContractAction, deleteContractAction } from "@/lib/actions/people/contracts";
import {
  listDepartments,
  createDepartmentAction,
  renameDepartmentAction,
  deleteDepartmentAction,
  moveEmployeeDepartmentAction,
} from "@/lib/actions/people/departments";
import {
  listEmployees,
  getEmployeeHub,
  createEmployeeAction,
  updateEmployeeAction,
  getProfileAction,
} from "@/lib/actions/people/employees";
import {
  listLeaveRequests,
  listMyLeaves,
  getLeaveCalendarMarkers,
  listMyLeaveFormOptions,
  applyLeaveAction,
  decideLeaveAction,
  getPaidLeaveBalance,
} from "@/lib/actions/people/leave";
import { listSchedules, getScheduleAction, upsertScheduleAction } from "@/lib/actions/people/schedules";
import { listTimeOffTypes, upsertTimeOffTypeAction, deleteTimeOffTypeAction } from "@/lib/actions/people/time-off-types";
import { getPayrollDashboard } from "@/lib/actions/payroll/payroll-dashboard";
import { listPayroll, getMyPayroll, upsertPayrollAction } from "@/lib/actions/payroll/payroll";
import {
  listEligibleEmployees,
  listPayruns,
  getPayrun,
  createPayrunAction,
  computePayrunAction,
  validatePayrunAction,
  markPayrunPaidAction,
  listPayslips,
  getPayslip,
  listMyPayslips,
  sendPayslipsAction,
  sendPayslipEmailAction,
  issueMonthEndPayslipsAction,
} from "@/lib/actions/payroll/payruns";
import {
  listSalaryStructures,
  getSalaryStructure,
  saveSalaryStructureAction,
  deleteSalaryStructureAction,
  listSalaryRules,
  saveSalaryRuleAction,
  deleteSalaryRuleAction,
} from "@/lib/actions/payroll/salary";
import {
  getPerformanceBoard,
  upsertPerformanceCycleAction,
  closePerformanceCycleAction,
  createPerformanceReviewAction,
  savePerformanceReviewAction,
  submitPerformanceReviewAction,
  deletePerformanceReviewAction,
  listMyPerformance,
  updateMyGoalProgressAction,
  acknowledgePerformanceReviewAction,
} from "@/lib/actions/performance";
import { updateMyProfileAction } from "@/lib/actions/profile";
import {
  getRecruitmentBoard,
  createJobOpeningAction,
  moveCandidateStageAction,
  rejectCandidateAction,
  scheduleCandidateInterviewAction,
} from "@/lib/actions/recruitment";
import { getCurrentUser, requireUser } from "@/lib/auth/session";
import { PIPELINE_STAGES } from "@/lib/recruitment/stages";
import {
  applyLeaveSchema,
  changePasswordSchema,
  copilotQuestionSchema,
  createDepartmentSchema,
  createEmployeeSchema,
  createPerformanceReviewSchema,
  decideLeaveSchema,
  moveEmployeeDepartmentSchema,
  performanceCycleSchema,
  savePerformanceReviewSchema,
  updateEmployeeSchema,
  updateMyGoalSchema,
  acknowledgeReviewSchema,
  upsertContractSchema,
  upsertPayrollSchema,
  upsertScheduleSchema,
  signUpSchema,
} from "@/lib/shared/validations";
import { defineOp, type ApiOperation } from "@/lib/api/v1/types";
import { employeeIdParam, idParam } from "@/lib/api/v1/schema";

const paginationQuery = z.object({
  page: z.coerce.number().int().min(1).optional(),
  pageSize: z.coerce.number().int().min(1).max(60).optional(),
  search: z.string().optional(),
  department: z.string().optional(),
  status: z.string().optional(),
  sort: z.string().optional(),
  dir: z.enum(["asc", "desc"]).optional(),
});

const employeeCodeQuery = z.object({
  employeeCode: z.string().optional(),
});

const dateRangeQuery = z.object({
  periodStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  periodEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  department: z.string().optional(),
  employeeType: z.enum(["full_time", "intern", "contractor"]).optional(),
});

const attendanceBody = z.object({
  id: z.string().optional(),
  userId: z.string().min(1),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  checkIn: z.string().optional().nullable(),
  checkOut: z.string().optional().nullable(),
  status: z.enum(["present", "absent", "half_day", "leave"]),
  notes: z.string().optional().nullable(),
});

const timeOffTypeBody = z.object({
  id: z.string().optional(),
  name: z.string().min(2),
  code: z.string().min(2).max(32),
  unit: z.enum(["days", "hours"]),
  requiresAllocation: z.boolean(),
  approver: z.enum(["manager", "officer"]),
  color: z.string().optional(),
  payrollNote: z.string().optional().nullable(),
});

const allocationBody = z.object({
  id: z.string().optional(),
  employeeProfileId: z.string().min(1),
  typeId: z.string().min(1),
  allocated: z.number().positive(),
  validityYear: z.number().int(),
  description: z.string().optional().nullable(),
});

const salaryStructureBody = z.object({
  id: z.string().optional(),
  name: z.string().min(2),
  active: z.boolean().optional(),
});

const salaryRuleBody = z.object({
  id: z.string().optional(),
  structureId: z.string().min(1),
  name: z.string().min(2),
  code: z.string().min(1),
  category: z.enum(["basic", "allowance", "gross", "deduction", "net", "contribution"]),
  sequence: z.number().int().min(1),
  computation: z.enum(["fixed", "percent_of_wage", "percent_of_basic", "percent_of_gross", "percent_of_category", "formula"]),
  amount: z.number().optional(),
  percentage: z.number().optional(),
  percentBaseCode: z.string().optional(),
  formula: z.string().optional(),
});

const payrunBody = z.object({
  name: z.string().min(2),
  structureId: z.string().min(1),
  periodStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  periodEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  employeeType: z.enum(["full_time", "intern", "contractor"]).optional().nullable(),
  employeeIds: z.array(z.string().min(1)).min(1),
});

const jobBody = z.object({
  title: z.string().min(1),
  department: z.string().min(1),
  deadline: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  description: z.string().optional(),
});

const preferencesBody = z.object({
  emailLeave: z.boolean(),
  emailRecruitment: z.boolean(),
  emailPerformance: z.boolean(),
  emailPayroll: z.boolean(),
  inApp: z.boolean(),
  sounds: z.boolean(),
});

export const apiOperations: ApiOperation[] = [
  defineOp({
    method: "get",
    path: "/health",
    operationId: "getHealth",
    summary: "Service health",
    description: "Unauthenticated liveness probe for load balancers.",
    tags: ["Meta"],
    public: true,
    handler: async () => ({ ok: true as const, data: { service: "hrms-api", version: "1.0.0" } }),
  }),
  defineOp({
    method: "post",
    path: "/organizations",
    operationId: "registerOrganization",
    summary: "Register a new organization",
    description: "Public self-serve tenant signup. Creates the company, founding admin, and default HR config, then signs the founder in.",
    tags: ["Account"],
    public: true,
    body: signUpSchema,
    handler: async ({ body }) => signUpOrganizationAction(body as Parameters<typeof signUpOrganizationAction>[0]),
  }),
  defineOp({
    method: "get",
    path: "/me",
    operationId: "getMe",
    summary: "Current session user",
    tags: ["Account"],
    handler: async () => {
      const user = await requireUser();
      return { ok: true, data: user };
    },
  }),
  defineOp({
    method: "get",
    path: "/me/profile",
    operationId: "getMyProfile",
    summary: "Current employee profile",
    tags: ["Account"],
    handler: async () => getProfileAction(),
  }),
  defineOp({
    method: "patch",
    path: "/me/profile",
    operationId: "updateMyProfile",
    summary: "Update my phone number",
    tags: ["Account"],
    body: z.object({ phone: z.string().max(40).optional() }),
    handler: async ({ body }) => updateMyProfileAction(body as { phone?: string }),
  }),
  defineOp({
    method: "post",
    path: "/me/password",
    operationId: "changePassword",
    summary: "Change password",
    tags: ["Account"],
    body: changePasswordSchema,
    handler: async ({ body }) => changePasswordAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/dashboards/admin",
    operationId: "getAdminDashboard",
    summary: "Admin workforce dashboard",
    tags: ["Dashboards"],
    handler: async () => getAdminDashboard(),
  }),
  defineOp({
    method: "get",
    path: "/dashboards/employee",
    operationId: "getEmployeeDashboard",
    summary: "Employee home dashboard",
    tags: ["Dashboards"],
    handler: async () => getEmployeeDashboard(),
  }),
  defineOp({
    method: "get",
    path: "/dashboards/payroll",
    operationId: "getPayrollDashboard",
    summary: "Payroll KPI dashboard",
    tags: ["Dashboards"],
    query: dateRangeQuery,
    handler: async ({ query }) => {
      const user = await getCurrentUser();
      if (!user) return { ok: false as const, error: "Your session expired. Please sign in again." };
      return getPayrollDashboard({
        user,
        periodStart: String(query.periodStart),
        periodEnd: String(query.periodEnd),
        department: query.department ? String(query.department) : undefined,
        employeeType: query.employeeType as "full_time" | "intern" | "contractor" | undefined,
      });
    },
  }),
  defineOp({
    method: "get",
    path: "/departments",
    operationId: "listDepartments",
    summary: "List departments",
    tags: ["Departments"],
    handler: async () => listDepartments(),
  }),
  defineOp({
    method: "post",
    path: "/departments",
    operationId: "createDepartment",
    summary: "Create a department",
    tags: ["Departments"],
    body: createDepartmentSchema,
    handler: async ({ body }) => createDepartmentAction(body as { name: string; code?: string }),
  }),
  defineOp({
    method: "patch",
    path: "/departments/{id}",
    operationId: "renameDepartment",
    summary: "Rename a department",
    tags: ["Departments"],
    params: idParam,
    body: z.object({ name: z.string().min(2).max(80) }),
    handler: async ({ params, body }) =>
      renameDepartmentAction({ id: params.id, name: (body as { name: string }).name }),
  }),
  defineOp({
    method: "delete",
    path: "/departments/{id}",
    operationId: "deleteDepartment",
    summary: "Delete a department",
    tags: ["Departments"],
    params: idParam,
    handler: async ({ params }) => deleteDepartmentAction({ id: params.id }),
  }),
  defineOp({
    method: "post",
    path: "/departments/move-employee",
    operationId: "moveEmployeeDepartment",
    summary: "Move an employee to another department",
    tags: ["Departments"],
    body: moveEmployeeDepartmentSchema,
    handler: async ({ body }) => moveEmployeeDepartmentAction(body as { employeeId: string; departmentId: string }),
  }),
  defineOp({
    method: "get",
    path: "/employees",
    operationId: "listEmployees",
    summary: "List employees",
    tags: ["Employees"],
    query: paginationQuery,
    handler: async ({ query }) => listEmployees(query),
  }),
  defineOp({
    method: "post",
    path: "/employees",
    operationId: "createEmployee",
    summary: "Create an employee",
    description: "Requires create-users permission. Temporary credentials are emailed when mail is configured.",
    tags: ["Employees"],
    body: createEmployeeSchema,
    handler: async ({ body }) => createEmployeeAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/employees/{employeeId}",
    operationId: "getEmployee",
    summary: "Get employee hub",
    tags: ["Employees"],
    params: employeeIdParam,
    handler: async ({ params }) => getEmployeeHub(params.employeeId),
  }),
  defineOp({
    method: "patch",
    path: "/employees/{employeeId}",
    operationId: "updateEmployee",
    summary: "Update or deactivate an employee",
    tags: ["Employees"],
    params: employeeIdParam,
    body: updateEmployeeSchema.omit({ employeeId: true }),
    handler: async ({ params, body }) =>
      updateEmployeeAction({ ...(body as object), employeeId: params.employeeId } as never),
  }),
  defineOp({
    method: "get",
    path: "/schedules",
    operationId: "listSchedules",
    summary: "List working schedules",
    tags: ["Schedules"],
    handler: async () => listSchedules(),
  }),
  defineOp({
    method: "get",
    path: "/schedules/{id}",
    operationId: "getSchedule",
    summary: "Get a working schedule",
    tags: ["Schedules"],
    params: idParam,
    handler: async ({ params }) => getScheduleAction(params.id),
  }),
  defineOp({
    method: "put",
    path: "/schedules",
    operationId: "upsertSchedule",
    summary: "Create or update a working schedule",
    tags: ["Schedules"],
    body: upsertScheduleSchema,
    handler: async ({ body }) => upsertScheduleAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/contracts",
    operationId: "listContracts",
    summary: "List contracts",
    tags: ["Contracts"],
    query: employeeCodeQuery,
    handler: async ({ query }) => listContracts({ employeeCode: query.employeeCode as string | undefined }),
  }),
  defineOp({
    method: "get",
    path: "/contracts/options",
    operationId: "getContractFormOptions",
    summary: "Contract form options",
    tags: ["Contracts"],
    handler: async () => getContractFormOptions(),
  }),
  defineOp({
    method: "get",
    path: "/contracts/{id}",
    operationId: "getContract",
    summary: "Get a contract",
    tags: ["Contracts"],
    params: idParam,
    handler: async ({ params }) => getContractAction(params.id),
  }),
  defineOp({
    method: "put",
    path: "/contracts",
    operationId: "upsertContract",
    summary: "Create or update a contract",
    tags: ["Contracts"],
    body: upsertContractSchema,
    handler: async ({ body }) => upsertContractAction(body as never),
  }),
  defineOp({
    method: "delete",
    path: "/contracts/{id}",
    operationId: "deleteContract",
    summary: "Delete a contract",
    tags: ["Contracts"],
    params: idParam,
    handler: async ({ params }) => deleteContractAction(params.id),
  }),
  defineOp({
    method: "get",
    path: "/attendance",
    operationId: "listAttendance",
    summary: "List attendance logs",
    tags: ["Attendance"],
    query: employeeCodeQuery,
    handler: async ({ query }) => listAttendanceLogs({ employeeCode: query.employeeCode as string | undefined }),
  }),
  defineOp({
    method: "get",
    path: "/attendance/employees",
    operationId: "listAttendanceEmployees",
    summary: "Employees available for attendance edits",
    tags: ["Attendance"],
    handler: async () => listAttendanceEmployees(),
  }),
  defineOp({
    method: "get",
    path: "/attendance/me",
    operationId: "listMyAttendance",
    summary: "My attendance history",
    tags: ["Attendance"],
    handler: async () => listMyAttendance(),
  }),
  defineOp({
    method: "get",
    path: "/attendance/today",
    operationId: "getTodayAttendance",
    summary: "My attendance today",
    tags: ["Attendance"],
    handler: async () => {
      const data = await getTodayAttendance();
      return { ok: true as const, data };
    },
  }),
  defineOp({
    method: "get",
    path: "/attendance/{id}",
    operationId: "getAttendance",
    summary: "Get one attendance row",
    tags: ["Attendance"],
    params: idParam,
    handler: async ({ params }) => getAttendanceAction(params.id),
  }),
  defineOp({
    method: "put",
    path: "/attendance",
    operationId: "upsertAttendance",
    summary: "Create or update an attendance row",
    tags: ["Attendance"],
    body: attendanceBody,
    handler: async ({ body }) => upsertAttendanceAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/attendance/clock-in",
    operationId: "clockIn",
    summary: "Clock in",
    tags: ["Attendance"],
    handler: async () => clockInAction(),
  }),
  defineOp({
    method: "post",
    path: "/attendance/clock-out",
    operationId: "clockOut",
    summary: "Clock out",
    tags: ["Attendance"],
    handler: async () => clockOutAction(),
  }),
  defineOp({
    method: "get",
    path: "/leave",
    operationId: "listLeaveRequests",
    summary: "List leave requests",
    tags: ["Leave"],
    handler: async () => listLeaveRequests(),
  }),
  defineOp({
    method: "get",
    path: "/leave/me",
    operationId: "listMyLeaves",
    summary: "My leave requests",
    tags: ["Leave"],
    handler: async () => listMyLeaves(),
  }),
  defineOp({
    method: "get",
    path: "/leave/calendar",
    operationId: "getLeaveCalendar",
    summary: "Leave calendar markers",
    tags: ["Leave"],
    handler: async () => getLeaveCalendarMarkers(),
  }),
  defineOp({
    method: "get",
    path: "/leave/options",
    operationId: "listMyLeaveFormOptions",
    summary: "Leave application options",
    tags: ["Leave"],
    handler: async () => listMyLeaveFormOptions(),
  }),
  defineOp({
    method: "get",
    path: "/leave/balance",
    operationId: "getPaidLeaveBalance",
    summary: "Paid leave balance",
    tags: ["Leave"],
    handler: async () => {
      const data = await getPaidLeaveBalance();
      return { ok: true as const, data };
    },
  }),
  defineOp({
    method: "post",
    path: "/leave",
    operationId: "applyLeave",
    summary: "Apply for leave",
    tags: ["Leave"],
    body: applyLeaveSchema,
    handler: async ({ body }) => applyLeaveAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/leave/{id}/decision",
    operationId: "decideLeave",
    summary: "Approve or reject leave",
    tags: ["Leave"],
    params: idParam,
    body: decideLeaveSchema.omit({ leaveId: true }),
    handler: async ({ params, body }) =>
      decideLeaveAction({ ...(body as object), leaveId: params.id } as never),
  }),
  defineOp({
    method: "get",
    path: "/time-off-types",
    operationId: "listTimeOffTypes",
    summary: "List time-off types",
    tags: ["Leave"],
    handler: async () => listTimeOffTypes(),
  }),
  defineOp({
    method: "put",
    path: "/time-off-types",
    operationId: "upsertTimeOffType",
    summary: "Create or update a time-off type",
    tags: ["Leave"],
    body: timeOffTypeBody,
    handler: async ({ body }) => upsertTimeOffTypeAction(body as never),
  }),
  defineOp({
    method: "delete",
    path: "/time-off-types/{id}",
    operationId: "deleteTimeOffType",
    summary: "Delete a time-off type",
    tags: ["Leave"],
    params: idParam,
    handler: async ({ params }) => deleteTimeOffTypeAction({ id: params.id }),
  }),
  defineOp({
    method: "get",
    path: "/allocations",
    operationId: "listAllocations",
    summary: "List time-off allocations",
    tags: ["Leave"],
    query: employeeCodeQuery,
    handler: async ({ query }) => listAllocations({ employeeCode: query.employeeCode as string | undefined }),
  }),
  defineOp({
    method: "put",
    path: "/allocations",
    operationId: "upsertAllocation",
    summary: "Create or update an allocation",
    tags: ["Leave"],
    body: allocationBody,
    handler: async ({ body }) => upsertAllocationAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/allocations/{id}/decision",
    operationId: "decideAllocation",
    summary: "Approve or refuse an allocation",
    tags: ["Leave"],
    params: idParam,
    body: z.object({ decision: z.enum(["approved", "refused"]) }),
    handler: async ({ params, body }) =>
      decideAllocationAction({ id: params.id, decision: (body as { decision: "approved" | "refused" }).decision }),
  }),
  defineOp({
    method: "get",
    path: "/payroll",
    operationId: "listPayroll",
    summary: "List monthly payroll stubs",
    tags: ["Payroll"],
    handler: async () => listPayroll(),
  }),
  defineOp({
    method: "get",
    path: "/payroll/me",
    operationId: "getMyPayroll",
    summary: "My payroll stubs",
    tags: ["Payroll"],
    handler: async () => getMyPayroll(),
  }),
  defineOp({
    method: "put",
    path: "/payroll",
    operationId: "upsertPayroll",
    summary: "Upsert a payroll stub",
    tags: ["Payroll"],
    body: upsertPayrollSchema,
    handler: async ({ body }) => upsertPayrollAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/payruns",
    operationId: "listPayruns",
    summary: "List payruns",
    tags: ["Payroll"],
    handler: async () => listPayruns(),
  }),
  defineOp({
    method: "get",
    path: "/payruns/eligible-employees",
    operationId: "listEligibleEmployees",
    summary: "Employees eligible for a payrun",
    tags: ["Payroll"],
    query: z.object({
      employeeType: z.enum(["full_time", "intern", "contractor"]).optional(),
      search: z.string().optional(),
      page: z.coerce.number().optional(),
      pageSize: z.coerce.number().optional(),
    }),
    handler: async ({ query }) =>
      listEligibleEmployees({
        employeeType: query.employeeType as "full_time" | "intern" | "contractor" | undefined,
        search: query.search ? String(query.search) : undefined,
        page: query.page ? Number(query.page) : undefined,
        pageSize: query.pageSize ? Number(query.pageSize) : undefined,
      }),
  }),
  defineOp({
    method: "post",
    path: "/payruns",
    operationId: "createPayrun",
    summary: "Create a payrun",
    tags: ["Payroll"],
    body: payrunBody,
    handler: async ({ body }) => createPayrunAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/payruns/{id}",
    operationId: "getPayrun",
    summary: "Get a payrun",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => getPayrun(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payruns/{id}/compute",
    operationId: "computePayrun",
    summary: "Compute a payrun",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => computePayrunAction(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payruns/{id}/validate",
    operationId: "validatePayrun",
    summary: "Validate a payrun",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => validatePayrunAction(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payruns/{id}/mark-paid",
    operationId: "markPayrunPaid",
    summary: "Mark a payrun paid",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => markPayrunPaidAction(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payruns/{id}/send-payslips",
    operationId: "sendPayslips",
    summary: "Email unsent payslips for a payrun",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => sendPayslipsAction(params.id),
  }),
  defineOp({
    method: "get",
    path: "/payslips",
    operationId: "listPayslips",
    summary: "List payslips",
    tags: ["Payroll"],
    handler: async () => listPayslips(),
  }),
  defineOp({
    method: "get",
    path: "/payslips/me",
    operationId: "listMyPayslips",
    summary: "My payslips",
    tags: ["Payroll"],
    handler: async () => listMyPayslips(),
  }),
  defineOp({
    method: "get",
    path: "/payslips/{id}",
    operationId: "getPayslip",
    summary: "Get a payslip",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => getPayslip(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payslips/{id}/email",
    operationId: "emailPayslip",
    summary: "Email one payslip",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => sendPayslipEmailAction(params.id),
  }),
  defineOp({
    method: "post",
    path: "/payslips/month-end",
    operationId: "issueMonthEndPayslips",
    summary: "Issue month-end payslips",
    tags: ["Payroll"],
    body: z.object({ month: z.string().regex(/^\d{4}-\d{2}$/).optional() }),
    handler: async ({ body }) => issueMonthEndPayslipsAction((body as { month?: string }).month),
  }),
  defineOp({
    method: "get",
    path: "/salary/structures",
    operationId: "listSalaryStructures",
    summary: "List salary structures",
    tags: ["Payroll"],
    handler: async () => listSalaryStructures(),
  }),
  defineOp({
    method: "put",
    path: "/salary/structures",
    operationId: "saveSalaryStructure",
    summary: "Create or update a salary structure",
    tags: ["Payroll"],
    body: salaryStructureBody,
    handler: async ({ body }) => saveSalaryStructureAction(body as never),
  }),
  defineOp({
    method: "get",
    path: "/salary/structures/{id}",
    operationId: "getSalaryStructure",
    summary: "Get a salary structure",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => getSalaryStructure(params.id),
  }),
  defineOp({
    method: "delete",
    path: "/salary/structures/{id}",
    operationId: "deleteSalaryStructure",
    summary: "Delete a salary structure",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => deleteSalaryStructureAction(params.id),
  }),
  defineOp({
    method: "get",
    path: "/salary/rules",
    operationId: "listSalaryRules",
    summary: "List salary rules",
    tags: ["Payroll"],
    query: z.object({ structureId: z.string().optional() }),
    handler: async ({ query }) => listSalaryRules(query.structureId as string | undefined),
  }),
  defineOp({
    method: "put",
    path: "/salary/rules",
    operationId: "saveSalaryRule",
    summary: "Create or update a salary rule",
    tags: ["Payroll"],
    body: salaryRuleBody,
    handler: async ({ body }) => saveSalaryRuleAction(body as never),
  }),
  defineOp({
    method: "delete",
    path: "/salary/rules/{id}",
    operationId: "deleteSalaryRule",
    summary: "Delete a salary rule",
    tags: ["Payroll"],
    params: idParam,
    handler: async ({ params }) => deleteSalaryRuleAction(params.id),
  }),
  defineOp({
    method: "get",
    path: "/performance",
    operationId: "getPerformanceBoard",
    summary: "Performance board",
    tags: ["Performance"],
    query: z.object({
      page: z.coerce.number().optional(),
      pageSize: z.coerce.number().optional(),
      search: z.string().optional(),
      cycleId: z.string().optional(),
      status: z.string().optional(),
    }),
    handler: async ({ query }) =>
      getPerformanceBoard({
        page: query.page ? Number(query.page) : undefined,
        pageSize: query.pageSize ? Number(query.pageSize) : undefined,
        search: query.search ? String(query.search) : undefined,
        cycleId: query.cycleId ? String(query.cycleId) : undefined,
        status: query.status ? String(query.status) : undefined,
      }),
  }),
  defineOp({
    method: "put",
    path: "/performance/cycles",
    operationId: "upsertPerformanceCycle",
    summary: "Create or update a performance cycle",
    tags: ["Performance"],
    body: performanceCycleSchema,
    handler: async ({ body }) => upsertPerformanceCycleAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/performance/cycles/{id}/close",
    operationId: "closePerformanceCycle",
    summary: "Close a performance cycle",
    tags: ["Performance"],
    params: idParam,
    handler: async ({ params }) => closePerformanceCycleAction(params.id),
  }),
  defineOp({
    method: "post",
    path: "/performance/reviews",
    operationId: "createPerformanceReview",
    summary: "Create a performance review",
    tags: ["Performance"],
    body: createPerformanceReviewSchema,
    handler: async ({ body }) => createPerformanceReviewAction(body as never),
  }),
  defineOp({
    method: "put",
    path: "/performance/reviews",
    operationId: "savePerformanceReview",
    summary: "Save a draft review",
    tags: ["Performance"],
    body: savePerformanceReviewSchema,
    handler: async ({ body }) => savePerformanceReviewAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/performance/reviews/{id}/submit",
    operationId: "submitPerformanceReview",
    summary: "Submit a review",
    tags: ["Performance"],
    params: idParam,
    handler: async ({ params }) => submitPerformanceReviewAction(params.id),
  }),
  defineOp({
    method: "delete",
    path: "/performance/reviews/{id}",
    operationId: "deletePerformanceReview",
    summary: "Delete a review",
    tags: ["Performance"],
    params: idParam,
    handler: async ({ params }) => deletePerformanceReviewAction(params.id),
  }),
  defineOp({
    method: "get",
    path: "/performance/me",
    operationId: "listMyPerformance",
    summary: "My performance reviews",
    tags: ["Performance"],
    handler: async () => listMyPerformance(),
  }),
  defineOp({
    method: "patch",
    path: "/performance/goals/{id}",
    operationId: "updateMyGoalProgress",
    summary: "Update my goal progress",
    tags: ["Performance"],
    params: idParam,
    body: updateMyGoalSchema.omit({ goalId: true }),
    handler: async ({ params, body }) =>
      updateMyGoalProgressAction({ goalId: params.id, progress: (body as { progress: number }).progress }),
  }),
  defineOp({
    method: "post",
    path: "/performance/reviews/{id}/acknowledge",
    operationId: "acknowledgePerformanceReview",
    summary: "Acknowledge a review",
    tags: ["Performance"],
    params: idParam,
    body: acknowledgeReviewSchema.omit({ reviewId: true }),
    handler: async ({ params, body }) =>
      acknowledgePerformanceReviewAction({
        reviewId: params.id,
        employeeComments: (body as { employeeComments?: string }).employeeComments,
      }),
  }),
  defineOp({
    method: "get",
    path: "/recruitment",
    operationId: "getRecruitmentBoard",
    summary: "Recruitment board",
    tags: ["Recruitment"],
    handler: async () => getRecruitmentBoard(),
  }),
  defineOp({
    method: "post",
    path: "/recruitment/jobs",
    operationId: "createJobOpening",
    summary: "Create a job opening",
    tags: ["Recruitment"],
    body: jobBody,
    handler: async ({ body }) => createJobOpeningAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/recruitment/candidates/{id}/stage",
    operationId: "moveCandidateStage",
    summary: "Move a candidate on the pipeline",
    tags: ["Recruitment"],
    params: idParam,
    body: z.object({ stage: z.enum(PIPELINE_STAGES) }),
    handler: async ({ params, body }) =>
      moveCandidateStageAction({ candidateId: params.id, stage: (body as { stage: (typeof PIPELINE_STAGES)[number] }).stage }),
  }),
  defineOp({
    method: "post",
    path: "/recruitment/candidates/{id}/reject",
    operationId: "rejectCandidate",
    summary: "Reject a candidate",
    tags: ["Recruitment"],
    params: idParam,
    handler: async ({ params }) => rejectCandidateAction({ candidateId: params.id }),
  }),
  defineOp({
    method: "post",
    path: "/recruitment/candidates/{id}/interview",
    operationId: "scheduleCandidateInterview",
    summary: "Schedule an interview",
    tags: ["Recruitment"],
    params: idParam,
    body: z.object({
      date: z.string().min(1),
      time: z.string().min(1),
      type: z.string().min(1),
      interviewer: z.string().min(1),
    }),
    handler: async ({ params, body }) =>
      scheduleCandidateInterviewAction({ candidateId: params.id, ...(body as object) } as never),
  }),
  defineOp({
    method: "get",
    path: "/notifications",
    operationId: "listNotifications",
    summary: "My notifications",
    tags: ["Notifications"],
    query: z.object({
      page: z.coerce.number().optional(),
      pageSize: z.coerce.number().optional(),
    }),
    handler: async ({ query }) =>
      listMyNotifications({
        page: query.page ? Number(query.page) : undefined,
        pageSize: query.pageSize ? Number(query.pageSize) : undefined,
      }),
  }),
  defineOp({
    method: "post",
    path: "/notifications/{id}/read",
    operationId: "markNotificationRead",
    summary: "Mark a notification read",
    tags: ["Notifications"],
    params: idParam,
    body: z.object({ read: z.boolean().optional() }),
    handler: async ({ params, body }) =>
      markNotificationReadAction(params.id, (body as { read?: boolean }).read ?? true),
  }),
  defineOp({
    method: "post",
    path: "/notifications/read-all",
    operationId: "markAllNotificationsRead",
    summary: "Mark all notifications read",
    tags: ["Notifications"],
    handler: async () => markAllNotificationsReadAction(),
  }),
  defineOp({
    method: "delete",
    path: "/notifications/{id}",
    operationId: "deleteNotification",
    summary: "Delete a notification",
    tags: ["Notifications"],
    params: idParam,
    handler: async ({ params }) => deleteNotificationAction(params.id),
  }),
  defineOp({
    method: "delete",
    path: "/notifications",
    operationId: "clearNotifications",
    summary: "Clear all notifications",
    tags: ["Notifications"],
    handler: async () => clearNotificationsAction(),
  }),
  defineOp({
    method: "get",
    path: "/notifications/preferences",
    operationId: "getNotificationPreferences",
    summary: "Notification preferences",
    tags: ["Notifications"],
    handler: async () => getNotificationPreferences(),
  }),
  defineOp({
    method: "put",
    path: "/notifications/preferences",
    operationId: "saveNotificationPreferences",
    summary: "Save notification preferences",
    tags: ["Notifications"],
    body: preferencesBody,
    handler: async ({ body }) => saveNotificationPreferencesAction(body as never),
  }),
  defineOp({
    method: "post",
    path: "/notifications/announcements",
    operationId: "createAnnouncement",
    summary: "Post an organisation announcement",
    tags: ["Notifications"],
    body: z.object({ title: z.string().min(2), body: z.string().min(2) }),
    handler: async ({ body }) => createAnnouncementAction(body as { title: string; body: string }),
  }),
  defineOp({
    method: "get",
    path: "/ai/analytics",
    operationId: "getAiAnalytics",
    summary: "AI analytics snapshot",
    tags: ["AI"],
    query: z.object({ periodDays: z.coerce.number().int().min(7).max(90).optional() }),
    handler: async ({ query }) => getAiAnalytics(Number(query.periodDays ?? 30)),
  }),
  defineOp({
    method: "post",
    path: "/ai/insights",
    operationId: "generateAiInsights",
    summary: "Regenerate insight cards",
    tags: ["AI"],
    handler: async () => generateAiInsights(),
  }),
  defineOp({
    method: "post",
    path: "/ai/copilot",
    operationId: "askHrCopilot",
    summary: "Ask the HR assistant",
    tags: ["AI"],
    body: copilotQuestionSchema,
    handler: async ({ body }) => {
      const input = body as { question: string; conversationId?: string | null };
      return askHrCopilot(input.question, input.conversationId);
    },
  }),
  defineOp({
    method: "get",
    path: "/ai/copilot/conversations",
    operationId: "listCopilotConversations",
    summary: "List assistant threads",
    tags: ["AI"],
    handler: async () => listCopilotConversations(),
  }),
  defineOp({
    method: "get",
    path: "/ai/copilot/history",
    operationId: "listCopilotHistory",
    summary: "Assistant message history",
    tags: ["AI"],
    query: z.object({ conversationId: z.string().optional() }),
    handler: async ({ query }) => listCopilotHistory(query.conversationId as string | undefined),
  }),
  defineOp({
    method: "delete",
    path: "/ai/copilot/conversations/{id}",
    operationId: "deleteCopilotConversation",
    summary: "Delete an assistant thread",
    tags: ["AI"],
    params: idParam,
    handler: async ({ params }) => deleteCopilotConversationAction(params.id),
  }),
  defineOp({
    method: "delete",
    path: "/ai/copilot/conversations",
    operationId: "clearCopilotHistory",
    summary: "Clear assistant history",
    tags: ["AI"],
    handler: async () => clearCopilotHistoryAction(),
  }),
  defineOp({
    method: "post",
    path: "/ai/leave/{id}/brief",
    operationId: "summarizeLeaveForApprover",
    summary: "Generate a leave approval brief",
    tags: ["AI"],
    params: idParam,
    handler: async ({ params }) => summarizeLeaveForApprover(params.id),
  }),
];

export function findApiOperation(method: string, pathname: string) {
  const verb = method.toLowerCase();
  for (const operation of apiOperations) {
    if (operation.method !== verb) continue;
    const keys: string[] = [];
    const pattern = operation.path.replace(/\{([^}]+)\}/g, (_, key: string) => {
      keys.push(key);
      return "([^/]+)";
    });
    const match = pathname.match(new RegExp(`^${pattern}$`));
    if (!match) continue;
    const params: Record<string, string> = {};
    keys.forEach((key, index) => {
      params[key] = decodeURIComponent(match[index + 1] ?? "");
    });
    return { operation, params };
  }
  return null;
}
